title: Tianzhu Qin's Home
author: Tianzhu Qin
email: tianzhu.qin@outlook.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is how this guy grows up.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Tianzhu Qin	
  tagline: Future Data Scientist
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  tianzhuqin
    linkedIn: in/tianzhu-qin-bentham-900438155
    twitter: Maple_Optboy
    # instagram:
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: maple_optboy
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed